name: aigun_app
description: "AIGun is a disruptive and innovative AI automated trading platform"

publish_to: "none"

version: 1.0.87+87

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shimmer: ^3.0.0
  flutter_markdown: ^0.7.6+2
  web3dart: ^2.7.1
  money2: ^6.0.3
  qr_flutter: ^4.1.0
  toastification: ^2.3.0
  dio: ^5.4.1
  go_router: ^17.0.0
  flutter_svg: ^2.0.16
  flutter_bloc: ^9.0.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.0.0
  shared_preferences: ^2.3.4
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  logger: ^2.5.0
  sentry_flutter: ^9.7.0
  flutter_secure_storage: ^9.2.0
  umeng_common_sdk: ^1.2.9
  url_launcher: ^6.3.2
  pinput: ^5.0.1
  fluttertoast: ^8.2.12
  device_info_plus: ^11.5.0
  decimal: ^3.2.4
  visibility_detector: ^0.4.0+2
  chewie: ^1.12.1
  photo_view: ^0.15.0
  pull_to_refresh: ^2.0.0
  timezone: ^0.10.1
  envied: ^1.3.2
  lottie: ^3.3.1
  dotlottie_loader: ^0.0.5
  extended_nested_scroll_view: ^6.2.1
  crypto: ^3.0.6
  video_player: ^2.10.0
  webview_flutter: ^4.13.0
  extended_tabs: ^5.0.0
  flutter_popup: ^3.3.9
  pull_to_refresh_notification: ^3.1.1
  background_downloader: ^9.3.0
  package_info_plus: ^9.0.0
  permission_handler: ^12.0.1
  extended_sliver: ^2.1.3
  app_tracking_transparency: ^2.0.6+1
  audioplayers: ^6.5.1
  flutter_inappwebview: ^6.1.5
  k_chart: ^0.7.1
  connectivity_plus: ^7.0.0
  get_it: ^9.0.5
  flutter_timezone: ^5.0.1
  syncfusion_flutter_charts: ^31.2.5
  dio_smart_retry: ^7.0.1
  app_settings: ^6.1.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  solana_web3: ^0.1.3
  http: ^1.6.0
  web_socket_channel: ^2.4.0
  share_plus: ^12.0.1
  web: ^1.1.1
  readmore: ^3.0.0
  collection: ^1.19.1

dependency_overrides:
  pinenacl: ^0.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sentry_dart_plugin: ^3.1.1
  flutter_launcher_icons: ^0.14.4
  envied_generator: ^1.3.2
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  go_router_builder: ^4.1.1
  bloc_lint: ^0.3.5


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/aigun-logo.jpg"
  min_sdk_android: 21
  adaptive_icon_background: "#ffe438"
  adaptive_icon_foreground: "assets/images/logo/app-logo-foreground.png"
  android_mipmap: true
  web:
    generate: true
    image_path: "assets/images/logo/aigun-logo.jpg"
    background_color: "#ffe438"
    theme_color: "#0175C2"
  windows:
    generate: true
    image_path: "assets/images/logo/aigun-logo.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo/aigun-logo.jpg"
# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/logo/aigun-logo.png"
#   min_sdk_android: 21
#   adaptive_icon_background: "#FE6256"  # 
#   adaptive_icon_foreground: "assets/images/logo/app-logo-foreground.png"  # 

flutter:
  generate: true
  uses-material-design: true
  #  Swift Package Manager（，）
  # disable-swift-package-manager: true

  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/icons/
    - assets/images/chain/
    - assets/nav/
    - assets/tabbar/
    - assets/test/
    - assets/lottie/
    - assets/icons-settings/
    - assets/images/trending/
    - assets/images/splash/
    - assets/audio/

  fonts:
    - family: Zeroes1
      fonts:
        - asset: assets/fonts/zeroes/zeroes-one.otf
          weight: 400

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: flutter-aigun
  org: web3-py
